version: "3"

services:
  server-torneo:
    container_name: server-torneo
    build:
      context: ./microtorneos
    restart: always
    volumes:
      - type: bind
        source: ./microtorneos/server
        target: /usr/src/app/server
    command: bash -c "npm run start"

  db-mysql:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      - MYSQL_DATABASE=proyectosa
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    volumes:
      - type: volume
        source: db_persistent_data
        target: /var/lib/mysql
        volume:
         nocopy: true

volumes:
    db_persistent_data:
      driver: local