version: "3"

services:
  webserver:
    image: node:10
    container_name: gameserver
    volumes: 
    - .:/home/app
    working_dir: /home/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: >
      bash -c "npm install -g nodemon 
      && nodemon app/server.js"

  db:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      - MYSQL_DATABASE=sa
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    ports:
      - 9906:3306
    volumes: 
    - ./mysql:/var/lib/mysql